# Generated by Django 3.1.2 on 2020-12-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='', max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_type', models.CharField(max_length=11)),
                ('brand_and_model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('condition', models.CharField(blank=True, default='Good', max_length=4)),
                ('is_replaced', models.BooleanField(blank=True, default=False)),
                ('is_received', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('date_of_confirmation', models.DateField(default=None, null=True)),
                ('date_of_supply', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Software_capable_hardware',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aMgnt.hardware')),
                ('antivirus_up_to_date', models.BooleanField()),
                ('operating_system', models.CharField(max_length=100)),
                ('operating_system_up_to_date', models.BooleanField()),
            ],
            bases=('aMgnt.hardware',),
        ),
        migrations.CreateModel(
            name='Supplied_departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.CharField(blank=True, default='', max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aMgnt.department')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aMgnt.supply')),
            ],
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_replacement', models.DateField()),
                ('new_hardware', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='from_new_field', to='aMgnt.hardware')),
                ('old_hardware', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='from_old_hardware_field', to='aMgnt.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_incident', models.DateField()),
                ('is_severe', models.BooleanField()),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, default='Not Resolved', max_length=12)),
                ('date_of_resolution', models.DateField(null=True)),
                ('steps_taken_to_resolve', models.CharField(max_length=1000)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aMgnt.hardware')),
            ],
        ),
        migrations.AddField(
            model_name='hardware',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aMgnt.supply'),
        ),
        migrations.CreateModel(
            name='System_unit',
            fields=[
                ('software_capable_hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aMgnt.software_capable_hardware')),
                ('ms_office_up_to_date', models.BooleanField()),
                ('system_unit_name', models.CharField(max_length=100)),
                ('service_tag_code', models.CharField(max_length=100)),
                ('monitor_serial_number', models.CharField(max_length=100)),
                ('keyboard_serial_number', models.CharField(max_length=100)),
                ('mouse_serial_number', models.CharField(max_length=100)),
                ('printer_brand_and_model', models.CharField(blank=True, default='', max_length=100)),
                ('printer_serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('scanner_brand_and_model', models.CharField(blank=True, default='', max_length=100)),
                ('scanner_serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('modem_brand_and_model', models.CharField(blank=True, default='', max_length=100)),
                ('modem_serial_number', models.CharField(blank=True, default='', max_length=100)),
            ],
            bases=('aMgnt.software_capable_hardware',),
        ),
    ]
