# Generated by Django 3.1.2 on 2020-12-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aMgnt', '0001_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
