# Generated by Django 3.1.2 on 2020-12-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aMgnt', '0002_added_department_to_hardware_for_ease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplied_departments',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='supply',
            name='assigned_to',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplied_departments',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
