# Generated by Django 3.1.2 on 2020-12-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aMgnt', '0005_branch_table_has_is_active_column'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='department',
        ),
        migrations.DeleteModel(
            name='Supplied_departments',
        ),
    ]
