# Generated by Django 3.1.4 on 2021-01-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aMgnt', '0009_All_system_unit_serial_number_components_optional_for_initial_integration_of_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_unit',
            name='keyboard_serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_unit',
            name='modem_brand_and_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_unit',
            name='modem_serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_unit',
            name='monitor_serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_unit',
            name='mouse_serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_unit',
            name='printer_brand_and_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_unit',
            name='printer_serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_unit',
            name='scanner_brand_and_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_unit',
            name='scanner_serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_unit',
            name='service_tag_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
