# Generated by Django 3.1.4 on 2021-01-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aMgnt', '0011_auto_20210108_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
