# Generated by Django 3.1.4 on 2021-04-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aMgnt', '0012_auto_20210108_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
                ('reportingStaffName', models.CharField(max_length=100)),
                ('resolution', models.CharField(blank=True, default='', max_length=100)),
                ('resolved', models.IntegerField(default=0)),
                ('severity', models.BooleanField(default=False)),
            ],
        ),
    ]
