# Generated by Django 3.1.4 on 2021-05-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aMgnt', '0013_generalincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
