# Generated by Django 3.1.4 on 2021-09-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aMgnt', '0014_hardware_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralIncidentEmailNotificationsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(default=False, max_length=100)),
            ],
        ),
    ]
