# Generated by Django 3.1.4 on 2021-09-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aMgnt', '0015_generalincidentemailnotificationslist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralIncidentEmailNotificationsList',
        ),
    ]
