# Generated by Django 3.1.4 on 2021-01-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('teller_or_operator', models.CharField(max_length=100)),
                ('debit', models.CharField(max_length=100)),
                ('credit', models.CharField(max_length=100)),
            ],
        ),
    ]
