# Generated by Django 3.1.4 on 2021-01-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nMeet', '0002_chat_table_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='message',
            new_name='text',
        ),
    ]
