# Generated by Django 3.1.4 on 2021-02-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nMeet', '0003_chat_message_renamed_to_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='branch',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='branch',
            field=models.CharField(max_length=20),
        ),
    ]
