# Generated by Django 3.1.4 on 2021-03-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nMeet', '0004_time_stamps_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
