# Generated by Django 3.1.4 on 2021-04-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nMeet', '0005_dashboard_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_of_cancelled_fig', models.BigIntegerField()),
            ],
        ),
    ]
