# Generated by Django 3.1.4 on 2021-07-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nMeet', '0006_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=20)),
            ],
        ),
    ]
