# Generated by Django 3.1.4 on 2021-03-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_serial_number', models.CharField(default='', max_length=100)),
                ('final_serial_number', models.CharField(default='', max_length=100)),
                ('cancellation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Init',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_serial_number', models.CharField(max_length=100)),
                ('final_serial_number', models.CharField(max_length=100)),
                ('current_serial_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_quant', models.CharField(default='', max_length=100)),
                ('total_usage', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='', max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('acc_no', models.CharField(default='', max_length=100)),
                ('initial_serial_number', models.CharField(max_length=100)),
                ('final_serial_number', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
